---
title: "merge_datasets"
author: "Sahil & Catalina"
date: '`r format(Sys.time(), "%B %d, %Y")`'
output: github_document
---

```{r setup, include=T}
knitr::opts_chunk$set(echo = TRUE,
                      warning = FALSE, 
                      message = FALSE,
                      comment = NA)
library(tidyverse)
```


## Merge datasets
```{r}
# read in file names with .csv format in the directory
datasets_names <- list.files("data_prep_scripts/",pattern = ".csv")
# create a list with a list of all the cleaned datasets
dat <- vector("list",length(datasets_names))

for (i in 1:length(datasets_names)) {
        dat[[i]] <- read.csv(paste0("data_prep_scripts/",datasets_names[i]),stringsAsFactors = F)
          dat[[i]] <- dat[[i]] %>% mutate(latitude=ifelse(latitude==0,NA,latitude))
}

# bind the datastes
all_datasets <- bind_rows(dat) #%>% unique()

## assign uid
all_datasets <- all_datasets %>% mutate(id = 1:n())
```

```{r}
## apply rules
all_datasets <- all_datasets %>% 
  mutate(SNAP = ifelse(type %in% "Farmers Market", 1, SNAP),
         SNAP = ifelse(food_bucks %in% 1, 1, SNAP),
         FMNP = ifelse(food_bucks %in% 1, 1, FMNP),
         food_bucks = ifelse(type %in% "Farmers Market", 1, food_bucks))

## fix street one and street two to be address (per 07/03/2019 meeting)
all_datasets <- all_datasets %>% 
  mutate(address = ifelse(is.na(address) & !is.na(street_one), 
                          paste(street_one, "&", street_two), 
                          address)) 
```

```{r}
#check
sum(which(is.na(all_datasets$latitude) & all_datasets$latitude==0))
names(all_datasets)
```

```{r}
#write out as csv
write.csv(all_datasets,"merged_datasets.csv", row.names = FALSE)
```


